/**
 * Re-export collection paths from the centralized refs.ts file
 */

import {
  PARTNER_COLLECTION,
  USER_COLLECTION,
  PROFILE_COLLECTION,
  PACKAGE_COLLECTION,
  PROMO_CODE_COLLECTION,
  COUNTRY_COLLECTION,
  ESIM_COLLECTION,
  PAYMENT_COLLECTION,
  PRICE_LIST_COLLECTION,
  BOOKING_COLLECTION,
  MESSAGE_COLLECTION,
  CURRENCY_COLLECTION,
  API_LOG_COLLECTION
} from '../base/refs';

export {
  PARTNER_COLLECTION,
  USER_COLLECTION,
  PROFILE_COLLECTION,
  PACKAGE_COLLECTION,
  PROMO_CODE_COLLECTION,
  COUNTRY_COLLECTION,
  ESIM_COLLECTION,
  PAYMENT_COLLECTION,
  PRICE_LIST_COLLECTION,
  BOOKING_COLLECTION,
  MESSAGE_COLLECTION,
  CURRENCY_COLLECTION,
  API_LOG_COLLECTION
};