name: Build, Commit Dist, and Tag Version

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'

permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Firebase Admin SDK
        run: npm install firebase-admin@^12.2.0

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install jq for JSON parsing
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set up Firebase Authentication for Testing
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_ENCODED }}" | base64 --decode > "/home/runner/firebaseServiceAccount.json"
          chmod 644 /home/runner/firebaseServiceAccount.json
          
      - name: Verify Firebase Service Account
        run: |
          if [ -f "/home/runner/firebaseServiceAccount.json" ]; then
            echo "✅ Firebase service account file created successfully"
            echo "File size: $(wc -c < /home/runner/firebaseServiceAccount.json) bytes"
            echo "Project ID from service account: $(jq -r '.project_id' /home/runner/firebaseServiceAccount.json)"
          else
            echo "❌ Firebase service account file not found"
            exit 1
          fi

      - name: Run tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "/home/runner/firebaseServiceAccount.json"
          FIREBASE_PROJECT_ID: "hubby-esim-dev"
          NODE_ENV: "test"
          CI: "true"
        run: npm test

      - name: Test coverage report
        if: always()
        run: |
          echo "Test execution completed"
          echo "Firebase project used: ${{ env.FIREBASE_PROJECT_ID }}"
          
      - name: Handle test failures
        if: failure()
        run: |
          echo "❌ Tests failed! Check the test output above for details."
          echo "Firebase configuration used:"
          echo "- Project ID: ${{ env.FIREBASE_PROJECT_ID }}"
          echo "- Service Account: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
          echo "- Node Environment: ${{ env.NODE_ENV }}"

  build:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 15
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git authentication
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm install

      - run: npm run build

      - name: Check if dist/ has changes
        id: check_changes
        run: |
          git add dist/
          git diff --cached --exit-code || echo "changes=true" >> $GITHUB_ENV

      - name: Commit and Push compiled dist
        if: env.changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "chore: build dist [skip ci]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/hubbyesim/types.git
          git push origin main

      - name: Get latest tag
        if: env.changes == 'true'
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git tag --sort=-v:refname | head -n 1)
          echo "Latest tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Bump patch version and create new tag
        if: env.changes == 'true'
        id: bump_tag
        run: |
          if [ -z "${{ env.tag }}" ]; then
            NEW_TAG="v1.0.0"
          else
            VERSION=${{ env.tag }}
            VERSION=${VERSION#v} # remove leading v
            IFS='.' read -ra PARTS <<< "$VERSION"
            MAJOR=${PARTS[0]}
            MINOR=${PARTS[1]}
            PATCH=${PARTS[2]}
            PATCH=$((PATCH + 1))
            NEW_TAG="v${MAJOR}.${MINOR}.${PATCH}"
          fi
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Create GitHub Release
        if: env.changes == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: "Schemas ${{ env.NEW_TAG }}"
          body: |
            🛠 Auto-generated release for schema build.
            Changes based on updates in `src/`.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build-only job for PRs (no commits/tags/releases)
  build-pr:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 15
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm install

      - run: npm run build

      - name: Verify build output
        run: |
          echo "✅ Build completed successfully"
          echo "📁 Generated files in dist/:"
          ls -la dist/
          echo "📊 Build size:"
          du -sh dist/